### ISSUE TITLE
Python install issues

### ISSUE THREAD

**Issue by tbirdso** [spatial-image/spatial-image-multiscale#29]
Hi @thewtex, I am having trouble getting started with the required Python packages. Could you please verify whether you ran into the issues below?

From the readme:
```
git clone https://github.com/spatial-image/spatial-image-multiscale
cd spatial-image-multiscale
pip install -e '.[test]'
cid=$(grep 'IPFS_CID =' test/test_spatial_image_multiscale.py | cut -d ' ' -f 3 | tr -d '"')
# Needs ipfs, e.g. https://docs.ipfs.io/install/ipfs-desktop/
ipfs get -o ./test/data -- $cid
pytest
# Notebook tests
pytest --nbmake --nbmake-timeout=3000 examples/*ipynb
```

In practice I get this failure:
```
(venv-itk) C:\repos\spatial-image-multiscale>python -m pip install -e '.[test]'
ERROR: '.[test]' is not a valid editable requirement. It should either be a path to a local project or a VCS URL (beginning with bzr+http, bzr+https, bzr+ssh, bzr+sftp, bzr+ftp, bzr+lp, bzr+file, git+http, git+https, git+ssh, git+git, git+file, hg+file, hg+http, hg+https, hg+ssh, hg+static-http, svn+ssh, svn+http, svn+https, svn+svn, svn+file).
```

Attempting to manually install packages that I see in test files, I am getting an error for Python 3.8 when trying to install the `datatree` package:
```
(venv-itk) C:\repos\spatial-image-multiscale>python -m pip install datatree
Collecting datatree
  Using cached datatree-0.1.8.1.tar.gz (12 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\tom.birdsong\AppData\Local\Temp\pip-install-g2hxue_5\datatree_4dd0bd05116345d9ba3e9df6c83a0627\setup.py", line 4, in <module>
          from datatree import VERSION
        File "C:\Users\tom.birdsong\AppData\Local\Temp\pip-install-g2hxue_5\datatree_4dd0bd05116345d9ba3e9df6c83a0627\datatree\__init__.py", line 1, in <module>
          from .tree import Tree, n, Node, Name, __
        File "C:\Users\tom.birdsong\AppData\Local\Temp\pip-install-g2hxue_5\datatree_4dd0bd05116345d9ba3e9df6c83a0627\datatree\tree.py", line 1, in <module>
          from StringIO import StringIO
      ModuleNotFoundError: No module named 'StringIO'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

The file in the `Temp` folder is removed by PyPI when installation fails, I am not able to manually edit the offending `StringIO` line. Any suggestions here?

**Comment by thewtex** [comment]
Resolved via #30
